package_name: image_classification_model
folder: chest_xray
train_folder: train
val_folder: val
test_folder: test
subfolder: NORMAL
subfolder_d: PNEUMONIA
pipeline_name: image_classification_model
pipeline_save_file: image_classification_model_output_
pipeline_save_file_new: image_classification_model_new_output_
pipeline_save_file_model: model_image_classification_
pipeline_save_file_model_new: model_image_classification_new_
saved_enc: oh_encoder_
test_size: 0.2
random_state: 0
ACCEPTABLE_MODEL_DIFFERENCE: 0.5
epochs: 2
batch_size: 64
target_size: 150
rescaling_factor: 255
target_classes: 3
